module mrtc_rdtc_dual_core #(
  parameter int PHASES_PER_BEAT = mrtc_pkg::MRTC_PHASES_PER_BEAT,
  parameter int AXIS_DATA_W = mrtc_pkg::MRTC_COMPLEX_SAMPLE_W * PHASES_PER_BEAT,
  parameter int COMP_BLOCK_BYTES = mrtc_pkg::MRTC_COMP_BLOCK_BYTES
) (
  input logic clk,
  input logic rst_n,
  input logic lane0_soft_reset,
  input logic lane1_soft_reset,
  input logic i_clear_status,

  input logic [AXIS_DATA_W-1:0] s0_axis_tdata,
  input logic s0_axis_tvalid,
  output logic s0_axis_tready,
  input logic s0_axis_tlast,
  input logic [7:0] s0_axis_tuser,
  output logic [AXIS_DATA_W-1:0] m0_axis_tdata,
  output logic m0_axis_tvalid,
  input logic m0_axis_tready,
  output logic m0_axis_tlast,
  output logic [7:0] m0_axis_tuser,

  input logic [AXIS_DATA_W-1:0] s1_axis_tdata,
  input logic s1_axis_tvalid,
  output logic s1_axis_tready,
  input logic s1_axis_tlast,
  input logic [7:0] s1_axis_tuser,
  output logic [AXIS_DATA_W-1:0] m1_axis_tdata,
  output logic m1_axis_tvalid,
  input logic m1_axis_tready,
  output logic m1_axis_tlast,
  output logic [7:0] m1_axis_tuser,

  input logic [7:0] cfg0_codec_mode,
  input logic [7:0] cfg0_rice_mode,
  input logic [3:0] cfg0_fixed_k,
  input logic [15:0] cfg0_frame_id,
  input logic [15:0] cfg0_block_id,
  input logic [15:0] cfg0_tensor_spatial_size,
  input logic [15:0] cfg0_tensor_doppler_size,
  input logic [15:0] cfg0_tensor_range_size,
  input logic [7:0] cfg1_codec_mode,
  input logic [7:0] cfg1_rice_mode,
  input logic [3:0] cfg1_fixed_k,
  input logic [15:0] cfg1_frame_id,
  input logic [15:0] cfg1_block_id,
  input logic [15:0] cfg1_tensor_spatial_size,
  input logic [15:0] cfg1_tensor_doppler_size,
  input logic [15:0] cfg1_tensor_range_size,

  output logic lane0_busy,
  output logic lane0_done,
  output logic [31:0] lane0_raw_bytes,
  output logic [31:0] lane0_comp_bytes,
  output logic [31:0] lane0_num_blocks,
  output logic [31:0] lane0_error,
  output logic [31:0] lane0_input_stall_cycles,
  output logic [31:0] lane0_output_stall_cycles,
  output logic lane1_busy,
  output logic lane1_done,
  output logic [31:0] lane1_raw_bytes,
  output logic [31:0] lane1_comp_bytes,
  output logic [31:0] lane1_num_blocks,
  output logic [31:0] lane1_error,
  output logic [31:0] lane1_input_stall_cycles,
  output logic [31:0] lane1_output_stall_cycles
);
  logic [31:0] unused_raw_bypass0;
  logic [31:0] unused_raw_bypass1;

  mrtc_rdtc_engine_lane #(
    .PHASES_PER_BEAT(PHASES_PER_BEAT),
    .AXIS_DATA_W(AXIS_DATA_W),
    .COMP_BLOCK_BYTES(COMP_BLOCK_BYTES)
  ) u_lane0 (
    .clk,
    .rst_n,
    .i_soft_reset(lane0_soft_reset),
    .i_clear_status,
    .s_axis_raw_tdata(s0_axis_tdata),
    .s_axis_raw_tvalid(s0_axis_tvalid),
    .s_axis_raw_tready(s0_axis_tready),
    .s_axis_raw_tlast(s0_axis_tlast),
    .s_axis_raw_tuser(s0_axis_tuser),
    .m_axis_comp_tdata(m0_axis_tdata),
    .m_axis_comp_tvalid(m0_axis_tvalid),
    .m_axis_comp_tready(m0_axis_tready),
    .m_axis_comp_tlast(m0_axis_tlast),
    .m_axis_comp_tuser(m0_axis_tuser),
    .cfg_codec_mode(cfg0_codec_mode),
    .cfg_rice_mode(cfg0_rice_mode),
    .cfg_fixed_k(cfg0_fixed_k),
    .cfg_frame_id(cfg0_frame_id),
    .cfg_block_id(cfg0_block_id),
    .cfg_tensor_spatial_size(cfg0_tensor_spatial_size),
    .cfg_tensor_doppler_size(cfg0_tensor_doppler_size),
    .cfg_tensor_range_size(cfg0_tensor_range_size),
    .stat_busy(lane0_busy),
    .stat_done(lane0_done),
    .stat_raw_bytes(lane0_raw_bytes),
    .stat_comp_bytes(lane0_comp_bytes),
    .stat_num_blocks(lane0_num_blocks),
    .stat_error(lane0_error),
    .stat_raw_bypass_blocks(unused_raw_bypass0),
    .stat_stall_input_cycles(lane0_input_stall_cycles),
    .stat_stall_output_cycles(lane0_output_stall_cycles)
  );

  mrtc_rdtc_engine_lane #(
    .PHASES_PER_BEAT(PHASES_PER_BEAT),
    .AXIS_DATA_W(AXIS_DATA_W),
    .COMP_BLOCK_BYTES(COMP_BLOCK_BYTES)
  ) u_lane1 (
    .clk,
    .rst_n,
    .i_soft_reset(lane1_soft_reset),
    .i_clear_status,
    .s_axis_raw_tdata(s1_axis_tdata),
    .s_axis_raw_tvalid(s1_axis_tvalid),
    .s_axis_raw_tready(s1_axis_tready),
    .s_axis_raw_tlast(s1_axis_tlast),
    .s_axis_raw_tuser(s1_axis_tuser),
    .m_axis_comp_tdata(m1_axis_tdata),
    .m_axis_comp_tvalid(m1_axis_tvalid),
    .m_axis_comp_tready(m1_axis_tready),
    .m_axis_comp_tlast(m1_axis_tlast),
    .m_axis_comp_tuser(m1_axis_tuser),
    .cfg_codec_mode(cfg1_codec_mode),
    .cfg_rice_mode(cfg1_rice_mode),
    .cfg_fixed_k(cfg1_fixed_k),
    .cfg_frame_id(cfg1_frame_id),
    .cfg_block_id(cfg1_block_id),
    .cfg_tensor_spatial_size(cfg1_tensor_spatial_size),
    .cfg_tensor_doppler_size(cfg1_tensor_doppler_size),
    .cfg_tensor_range_size(cfg1_tensor_range_size),
    .stat_busy(lane1_busy),
    .stat_done(lane1_done),
    .stat_raw_bytes(lane1_raw_bytes),
    .stat_comp_bytes(lane1_comp_bytes),
    .stat_num_blocks(lane1_num_blocks),
    .stat_error(lane1_error),
    .stat_raw_bypass_blocks(unused_raw_bypass1),
    .stat_stall_input_cycles(lane1_input_stall_cycles),
    .stat_stall_output_cycles(lane1_output_stall_cycles)
  );
endmodule
