module mrtc_rdtc_codec_top #(
  parameter int AXIS_DATA_W = 128,
  parameter int MRTC_K_POLICY_ARCH = mrtc_pkg::MRTC_K_POLICY_FULL_ADAPTIVE,
  parameter bit PREFIX_STREAM_LENGTH_BY_TLAST = 1'b1,
  parameter int PREFIX_SAMPLES = 256
) (
  input  logic                   clk,
  input  logic                   rst_n,
  input  logic                   i_clear_status,
  input  logic [AXIS_DATA_W-1:0] s_axis_raw_tdata,
  input  logic                   s_axis_raw_tvalid,
  output logic                   s_axis_raw_tready,
  input  logic                   s_axis_raw_tlast,
  input  logic [7:0]             s_axis_raw_tuser,
  output logic [AXIS_DATA_W-1:0] m_axis_comp_tdata,
  output logic                   m_axis_comp_tvalid,
  input  logic                   m_axis_comp_tready,
  output logic                   m_axis_comp_tlast,
  output logic [7:0]             m_axis_comp_tuser,
  input  logic [AXIS_DATA_W-1:0] s_axis_comp_tdata,
  input  logic                   s_axis_comp_tvalid,
  output logic                   s_axis_comp_tready,
  input  logic                   s_axis_comp_tlast,
  input  logic [7:0]             s_axis_comp_tuser,
  output logic [AXIS_DATA_W-1:0] m_axis_raw_tdata,
  output logic                   m_axis_raw_tvalid,
  input  logic                   m_axis_raw_tready,
  output logic                   m_axis_raw_tlast,
  output logic [7:0]             m_axis_raw_tuser,
  input  logic [7:0]             cfg_codec_mode,
  input  logic [7:0]             cfg_rice_mode,
  input  logic [3:0]             cfg_fixed_k,
  input  logic [15:0]            cfg_frame_id,
  input  logic [15:0]            cfg_block_id_base,
  input  logic [15:0]            cfg_tensor_spatial_size,
  input  logic [15:0]            cfg_tensor_doppler_size,
  input  logic [15:0]            cfg_tensor_range_size,
  output logic                   stat_enc_busy,
  output logic                   stat_enc_done,
  output logic [31:0]            stat_enc_raw_bytes,
  output logic [31:0]            stat_enc_comp_bytes,
  output logic [31:0]            stat_enc_num_blocks,
  output logic [31:0]            stat_enc_error,
  output logic [31:0]            stat_enc_raw_bypass_blocks,
  output logic [31:0]            stat_enc_stall_input_cycles,
  output logic [31:0]            stat_enc_stall_output_cycles,
  output logic                   stat_dec_busy,
  output logic                   stat_dec_done,
  output logic [31:0]            stat_dec_comp_bytes,
  output logic [31:0]            stat_dec_raw_bytes,
  output logic [31:0]            stat_dec_num_blocks,
  output logic [31:0]            stat_dec_error,
  output logic [31:0]            stat_dec_error_blocks,
  output logic [31:0]            stat_dec_stall_input_cycles,
  output logic [31:0]            stat_dec_stall_output_cycles
);
  mrtc_rdtc_encoder_top #(
    .AXIS_DATA_W(AXIS_DATA_W),
    .MRTC_K_POLICY_ARCH(MRTC_K_POLICY_ARCH),
    .PREFIX_STREAM_LENGTH_BY_TLAST(PREFIX_STREAM_LENGTH_BY_TLAST),
    .PREFIX_SAMPLES(PREFIX_SAMPLES)
  ) u_encoder (
    .clk(clk),
    .rst_n(rst_n),
    .i_clear_status(i_clear_status),
    .s_axis_raw_tdata(s_axis_raw_tdata),
    .s_axis_raw_tvalid(s_axis_raw_tvalid),
    .s_axis_raw_tready(s_axis_raw_tready),
    .s_axis_raw_tlast(s_axis_raw_tlast),
    .s_axis_raw_tuser(s_axis_raw_tuser),
    .m_axis_comp_tdata(m_axis_comp_tdata),
    .m_axis_comp_tvalid(m_axis_comp_tvalid),
    .m_axis_comp_tready(m_axis_comp_tready),
    .m_axis_comp_tlast(m_axis_comp_tlast),
    .m_axis_comp_tuser(m_axis_comp_tuser),
    .cfg_codec_mode(cfg_codec_mode),
    .cfg_rice_mode(cfg_rice_mode),
    .cfg_fixed_k(cfg_fixed_k),
    .cfg_frame_id(cfg_frame_id),
    .cfg_block_id_base(cfg_block_id_base),
    .cfg_tensor_spatial_size(cfg_tensor_spatial_size),
    .cfg_tensor_doppler_size(cfg_tensor_doppler_size),
    .cfg_tensor_range_size(cfg_tensor_range_size),
    .stat_busy(stat_enc_busy),
    .stat_done(stat_enc_done),
    .stat_raw_bytes(stat_enc_raw_bytes),
    .stat_comp_bytes(stat_enc_comp_bytes),
    .stat_num_blocks(stat_enc_num_blocks),
    .stat_error(stat_enc_error),
    .stat_raw_bypass_blocks(stat_enc_raw_bypass_blocks),
    .stat_stall_input_cycles(stat_enc_stall_input_cycles),
    .stat_stall_output_cycles(stat_enc_stall_output_cycles)
  );

  mrtc_rdtc_decoder_top #(
    .AXIS_DATA_W(AXIS_DATA_W)
  ) u_decoder (
    .clk(clk),
    .rst_n(rst_n),
    .i_clear_status(i_clear_status),
    .s_axis_comp_tdata(s_axis_comp_tdata),
    .s_axis_comp_tvalid(s_axis_comp_tvalid),
    .s_axis_comp_tready(s_axis_comp_tready),
    .s_axis_comp_tlast(s_axis_comp_tlast),
    .s_axis_comp_tuser(s_axis_comp_tuser),
    .m_axis_raw_tdata(m_axis_raw_tdata),
    .m_axis_raw_tvalid(m_axis_raw_tvalid),
    .m_axis_raw_tready(m_axis_raw_tready),
    .m_axis_raw_tlast(m_axis_raw_tlast),
    .m_axis_raw_tuser(m_axis_raw_tuser),
    .stat_busy(stat_dec_busy),
    .stat_done(stat_dec_done),
    .stat_comp_bytes(stat_dec_comp_bytes),
    .stat_raw_bytes(stat_dec_raw_bytes),
    .stat_num_blocks(stat_dec_num_blocks),
    .stat_error(stat_dec_error),
    .stat_error_blocks(stat_dec_error_blocks),
    .stat_stall_input_cycles(stat_dec_stall_input_cycles),
    .stat_stall_output_cycles(stat_dec_stall_output_cycles)
  );
endmodule
